-- Users table
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  otp CHAR(4) NOT NULL,
  otp_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
